language: cpp
compiler: gcc

dist: trusty
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - build-essential
        - iverilog
        - lcov
        - valgrind
        - texinfo
        - binutils-dev

before_install:
  # C++17
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install: 
  # C++17
  - sudo apt-get install gcc-7 g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  # llvm
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-8 main"
  - sudo apt-get update
  - sudo apt-get install llvm-8-dev

script: 
  # patch libjit
  - scripts/libjit_patch.sh  
  # Build llvm Release project
  - mkdir -p build_llr
  - pushd build_llr
  - cmake -DLLVMJIT=ON -DCMAKE_BUILD_TYPE=Release ..
  - make -j8 all
  - make test   
  - CASH_CFLAGS=256 make test    # Turn off JIT
  - CASH_CFLAGS=640 make test    # Turn off CFO/SUB opts
  - CASH_CFLAGS=261760 make test # Turn off all opts
  - valgrind bin/testsuite
  - CASH_CFLAGS=256 valgrind bin/testsuite
  - CASH_CFLAGS=640 valgrind bin/testsuite
  - CASH_CFLAGS=261760 valgrind bin/testsuite
  - popd
  # Build libjit Release project
  - mkdir -p build_jbr
  - pushd build_jbr
  - cmake -DLIBJIT=ON -DCMAKE_BUILD_TYPE=Release ..
  - make -j8 all
  - make test
  - CASH_CFLAGS=256 make test
  - CASH_CFLAGS=640 make test
  - CASH_CFLAGS=261760 make test
  - valgrind bin/testsuite
  - CASH_CFLAGS=256 valgrind bin/testsuite
  - CASH_CFLAGS=640 valgrind bin/testsuite
  - CASH_CFLAGS=261760 valgrind bin/testsuite
  - popd
  # Build llvm Debug project
  - export CASH_DEBUG_LEVEL=3
  - mkdir -p build_lld
  - pushd build_lld
  - cmake -DLLVMJIT=ON -DCMAKE_BUILD_TYPE=Debug -DCODECOV=ON ..
  - make -j8 all 
  - CASH_CFLAGS=15  make test
  - CASH_CFLAGS=271 make test
  - CASH_CFLAGS=655 make test
  - CASH_CFLAGS=261775 make test
  - popd  
  
after_success:
  # Gather code coverage
  - lcov --directory . --capture --output-file coverage.info # capture trace  
  - lcov --list coverage.info # trace report
  # Upload coverage report
  - bash <(curl -s https://codecov.io/bash)
