language: cpp
compiler: gcc
dist: trusty
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - binutils-dev

before_install:
  # C++17
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install: 
  # C++17
  - sudo apt-get install gcc-7 g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7

script: 
  - source env.sh 
  - cd src
  - make
  - cd example
  - make run
  - cd ..
  - cd test
  - make run

git:
  submodules: false

notifications:
    email:
        recipients:
            - cash.gtcasl@gmail.com
        on_success: change
        on_failure: always
