language: cpp
compiler: gcc

dist: trusty
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - build-essential
        - binutils-dev
        - iverilog
        - lcov
        - valgrind

install:
  # update system
  - sudo apt-get update 
  - sudo apt-get autoremove 
  - sudo apt-get autoclean
  # LIBJIT
  - sudo apt-get install libtool autoconf flex bison texinfo
  - git clone https://git.savannah.gnu.org/git/libjit.git
  - pushd libjit
  - git apply ../scripts/libjit.patch
  - ./bootstrap
  - mkdir build
  - pushd build
  - ../configure --with-pic
  - make -j8 all
  - sudo make install
  - popd
  - popd
  # GCC-7
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-7 g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  # LLVM-8
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-8 main"
  - sudo apt-get update
  - sudo apt-get install llvm-8-dev

script: 
  # Build LLVM Release project
  - mkdir -p build_llr
  - pushd build_llr
  - cmake -DJIT=LLVM -DCMAKE_BUILD_TYPE=Release ..
  - make -j8 all
  - make test   
  - CASH_CFLAGS=256 make test    # Turn off JIT
  - CASH_CFLAGS=261760 make test # Turn off all opts
  #- valgrind bin/testsuite
  - pushd tests
  - CASH_CFLAGS=262016 valgrind ../bin/testsuite
  - CASH_CFLAGS=256 valgrind ../bin/testsuite
  - popd
  - popd
  # Build LIBJIT Release project
  - mkdir -p build_jbr
  - pushd build_jbr
  - cmake -DJIT=LIBJIT -DCMAKE_BUILD_TYPE=Release ..
  - make -j8 all
  - make test
  - CASH_CFLAGS=261760 make test
  - pushd tests
  - valgrind ../bin/testsuite
  - CASH_CFLAGS=261760 valgrind ../bin/testsuite
  - popd
  - popd
  # Build LLVM Debug project
  - export CASH_DEBUG_LEVEL=3
  - mkdir -p build_lld
  - pushd build_lld
  - cmake -DJIT=LLVM -DCMAKE_BUILD_TYPE=Debug -DCODECOV=ON ..
  - make -j8 all 
  - CASH_CFLAGS=15  make test
  - CASH_CFLAGS=271 make test
  - CASH_CFLAGS=261775 make test
  - popd  
  
after_success:
  # Gather code coverage
  - lcov --directory . --capture --output-file coverage.info # capture trace  
  - lcov --list coverage.info # trace report
  # Upload coverage report
  - bash <(curl -s https://codecov.io/bash)
