language: cpp
compiler: gcc

dist: trusty
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - iverilog
        - binutils-dev
        - lcov

before_install:
  # C++17
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install: 
  # C++17
  - sudo apt-get install gcc-7 g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7

script: 
  # set test environment variables
  - export CASH_DEBUG_LEVEL=2
  - export CASH_CFLAGS=15

  # Build project
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCODECOV=ON ..
  - make -j8
  # Run tests
  - make test
  
after_success:
  # Gather code coverage
  - lcov --directory . --capture --output-file coverage.info # capture trace  
  - lcov --list coverage.info # trace report
  # Upload coverage report
  - bash <(curl -s https://codecov.io/bash)
