language: cpp
compiler: gcc

dist: bionic
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - build-essential
        - iverilog
        - valgrind
        - lcov

install:
  # LIBJIT
  - sudo apt-get install libtool autoconf flex bison texinfo
  - git clone https://git.savannah.gnu.org/git/libjit.git
  - pushd libjit
  - git apply ../scripts/libjit.patch
  - ./bootstrap
  - mkdir build
  - pushd build
  - ../configure --with-pic
  - make -j`nproc` all
  - sudo make install
  - popd
  - popd
  # LLVM-8
  - sudo apt-get update
  - sudo apt-get install llvm-8-dev libclang-8-dev

script: 
  - scripts/regression.sh ..
  
after_success:
  # Gather code coverage
  - lcov --directory . --capture --output-file coverage.info # capture trace  
  - lcov --list coverage.info # trace report
  # Upload coverage report
  - bash <(curl -s https://codecov.io/bash)
