title: Cash
description: A C++ API and Simulator for Hardware.
show_downloads: true
google_analytics: UA-112772241-1
theme: jekyll-theme-cayman

# logo image to use. logo images are constrained at 50px in height.
logo: assets/cash_logo.png

# email address feedback gets sent to
feedback_email: blaise-tine@gmail.com

